name: Build_wheels on macOS all images
on: [workflow_dispatch]
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        #os: [ubuntu-latest, windows-latest, macos-13, macos-14]
         os: ['macos-14','macos-13', 'macos-14-large','macos-13-xlarge']
    steps:
      - uses: actions/checkout@v4
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.18.1
        env:
          CIBW_SKIP: "*musllinux*"
          CIBW_ENVIRONMENT: MACOSX_DEPLOYMENT_TARGET=10.14
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
